### ISSUE TITLE
Checklist: 0.6.0 release

### ISSUE THREAD

**Issue by phurwicz** [phurwicz/hover#23]
In this specific order:

- [x] core and recipe signatures locked in 
- [x] all source code locked in
- [x] full automated test on different OS
- [x] manual interaction tests @phurwicz @haochuanwei 
- [x] check CHANGELOG
- [x] check setup.py and conda recipe
- [x] check README and description
- [x] [published to PyPI](https://pypi.org/project/hover/0.6.0/)
- [x] [published to conda-forge](https://github.com/conda-forge/staged-recipes/pull/18038)
