### ISSUE TITLE
Checklist: 0.7.0 release

### ISSUE THREAD

**Issue by phurwicz** [phurwicz/hover#25]
In this specific order:

- [x] core and recipe signatures locked in 
- [x] all source code locked in
- [x] full automated test on different OS
- [x] manual interaction tests @phurwicz @haochuanwei 
- [x] check CHANGELOG
- [x] check setup.py and conda recipe
- [x] check README and description
- [x] [published to PyPI](https://pypi.org/project/hover/0.7.0/)
- [x] [published to conda-forge](https://anaconda.org/conda-forge/hover)

**Comment by haochuanwei** [comment]
Completed. The tutorials on the doc site are also verified.
